[general]
static = yes
writeprotect = yes
autofallthrough = yes
clearglobalvars = yes

; Subroutine to call all internal phones until one answers
[CallToAllPhones]
exten => s, 1, Dial(PJSIP/100 & PJSIP/101, 30, rT)
 same => n, Return()

[internal]
; Example internal phones (1XX)
exten => _1XX, 1, Dial(PJSIP/${EXTEN}, 30, rT)

; Hackfed – Loopback
; Replace 7509123 with your prefix.
exten => _7509123., 1, Dial(PJSIP/${EXTEN:7}, 30, rT)

; Hackfed – this include must be in context of your outbound calls
#include hackfed/extensions-outbound.conf

; Hackfed – Define a "HackfedIncomingRouter" subroutine to route calls from Hackfed peers
; hackfedd-generated trunks will Gosub to this with the called number as ARG1
[HackfedIncomingRouter]
exten => s, 1, GotoIf($["${ARG1:7}" = ""] ? CallAll : Direct)
 same => n(CallAll), Gosub(CallToAllPhones, s, 1)
 same => n, Return()
 same => n(Direct), Dial(PJSIP/${ARG1:7}, 30)
 same => n, Return()

; Hackfed – Inbound contexts
; Place this at the end of your extensions.conf
#include hackfed/extensions-inbound.conf
