; AMI - The Asterisk Manager Interface
; Hackfedd needs it to reload IAX2 and dialplan configuration on directory changes.
[general]
enabled = yes
webenabled = yes

[hackfedd]
secret = your_generated_password_here
read = system,config,command
write = system,config,command

; You should adjust allowed IPs according to your network setup and where hackfedd resides.
deny = 0.0.0.0/0.0.0.0
permit = 172.16.0.0/12
