import type {
  TelephonyDirectory,
  TelephonyDirectoryExchange,
} from '@hackfed/schemas/v1'

import { Eta } from 'eta'
import { createHash } from 'node:crypto'
import { isIP } from 'node:net'

import inboundTemplate from './templates/extensions-inbound.eta' with { type: 'text' }
import outboundTemplate from './templates/extensions-outbound.eta' with { type: 'text' }
import iaxTemplate from './templates/iax.eta' with { type: 'text' }

export interface AsteriskArtifacts {
  'extensions-inbound.conf': string
  'extensions-outbound.conf': string
  'iax.conf': string
}

export interface AsteriskModel {
  localPeerName: string
  localPrefix: string
  localShortName: string
  peers: AsteriskPeer[]
}

export type AsteriskModule = 'chan_iax2.so' | 'pbx_config.so'

export interface AsteriskPeer {
  codecs: TelephonyDirectoryExchange['codecs']
  context: string
  displayName: string
  host: string
  orgId: string
  peerName: string
  port: number
  prefix: string
  shortName: string
}

export interface BuildAsteriskModelOptions {
  exchangeId: string
  ignoredOrgs?: string[]
  orgId: string
}

const GENERATED_HEADER = `; This file is auto-generated by hackfedd.
; DO NOT EDIT THIS FILE MANUALLY. Your changes will be lost.
`
// Asterisk configuration is plain text; HTML escaping and newline trimming alter its syntax.
const eta = new Eta({ autoEscape: false, autoTrim: false })

export function buildAsteriskModel (
  directory: TelephonyDirectory,
  options: BuildAsteriskModelOptions
): AsteriskModel {
  const localOrg = directory.orgs.find(org => org.orgId === options.orgId)
  if (!localOrg) {
    throw new Error(`Telephony directory does not contain local organization "${options.orgId}"`)
  }

  const localExchanges = localOrg.exchanges.filter(exchange => exchange.id === options.exchangeId)
  if (localExchanges.length !== 1) {
    throw new Error(
      `Telephony directory must contain exactly one local exchange "${options.orgId}/${options.exchangeId}"; found ${localExchanges.length}`
    )
  }

  const localExchange = localExchanges[0]
  if (!localExchange) {
    throw new Error('Local telephony exchange selection failed unexpectedly')
  }

  // Validate the local endpoint as well, even though it is not rendered as a peer.
  parseEndpoint(localExchange.endpoint)
  const localPeerName = makePeerName(options.orgId, options.exchangeId)
  const localPrefix = normalizePrefix(localExchange.prefix)
  const localShortName = sanitizeDisplayText(localOrg.orgId)
  const ignoredOrgs = new Set(options.ignoredOrgs)
  const peerNames = new Set([localPeerName])
  const peers: AsteriskPeer[] = []

  for (const org of directory.orgs) {
    if (ignoredOrgs.has(org.orgId)) {
      continue
    }

    const remoteExchanges = org.exchanges.filter(exchange =>
      !(org.orgId === options.orgId && exchange.id === options.exchangeId))
    for (const exchange of remoteExchanges) {
      const { host, port } = parseEndpoint(exchange.endpoint)
      const codecs = localExchange.codecs.filter(codec => exchange.codecs.includes(codec))
      if (codecs.length === 0) {
        throw new Error(`No common codec for telephony exchange "${org.orgId}/${exchange.id}"`)
      }

      const peerName = makePeerName(org.orgId, exchange.id)
      if (peerNames.has(peerName)) {
        throw new Error(`Duplicate telephony exchange identity "${org.orgId}/${exchange.id}"`)
      }
      peerNames.add(peerName)

      peers.push({
        codecs,
        context: `${peerName}-in`,
        displayName: sanitizeDisplayText(org.name),
        host,
        orgId: org.orgId,
        peerName,
        port,
        prefix: normalizePrefix(exchange.prefix),
        shortName: sanitizeDisplayText(org.orgId),
      })
    }
  }

  peers.sort(comparePeers)

  const prefixes = new Set([localPrefix])
  for (const peer of peers) {
    if (prefixes.has(peer.prefix)) {
      throw new Error(`Duplicate telephony prefix "+${peer.prefix}"`)
    }
    prefixes.add(peer.prefix)
  }

  return { localPeerName, localPrefix, localShortName, peers }
}

export function makePeerName (orgId: string, exchangeId: string): string {
  const safeOrgId = orgId.toLowerCase().replaceAll(/[^a-z0-9]/g, '-')
  const slug = exchangeId
    .normalize('NFKD')
    .toLowerCase()
    .replaceAll(/[^a-z0-9]+/g, '-')
    .replaceAll(/^-+|-+$/g, '')
    .slice(0, 24) || 'exchange'
  const hash = createHash('sha256')
    .update(`${orgId}\0${exchangeId}`)
    .digest('hex')
    .slice(0, 12)

  return `hf-${safeOrgId}-${slug}-${hash}`
}

export function normalizePrefix (prefix: string): string {
  const normalized = prefix.startsWith('+') ? prefix.slice(1) : prefix
  if (!/^[1-9][0-9]*$/.test(normalized)) {
    throw new Error(`Invalid E.164 telephony prefix "${prefix}"`)
  }
  return normalized
}

export function parseEndpoint (endpoint: string): { host: string, port: number } {
  const ipv6 = /^\[([^\]]+)]:(\d{1,5})$/.exec(endpoint)
  const ipv4 = /^([^:]+):(\d{1,5})$/.exec(endpoint)
  const match = ipv6 ?? ipv4
  if (!match) {
    throw new Error(`Invalid telephony endpoint "${endpoint}"; expected [IPv6]:port or IPv4:port`)
  }

  const host = match[1]
  const portText = match[2]
  if (!host || !portText || isIP(host) === 0) {
    throw new Error(`Invalid IP address in telephony endpoint "${endpoint}"`)
  }

  const port = Number(portText)
  if (!Number.isSafeInteger(port) || port < 1 || port > 65_535) {
    throw new Error(`Invalid port in telephony endpoint "${endpoint}"`)
  }

  return { host, port }
}

export function renderAsteriskArtifacts (model: AsteriskModel): AsteriskArtifacts {
  return {
    'extensions-inbound.conf': renderAsteriskTemplate(inboundTemplate, model),
    'extensions-outbound.conf': renderAsteriskTemplate(outboundTemplate, model),
    'iax.conf': renderAsteriskTemplate(iaxTemplate, model),
  }
}

function comparePeers (left: AsteriskPeer, right: AsteriskPeer): number {
  return left.orgId.localeCompare(right.orgId) ||
    left.peerName.localeCompare(right.peerName) ||
    left.prefix.localeCompare(right.prefix) ||
    left.host.localeCompare(right.host) ||
    left.port - right.port
}

function renderAsteriskTemplate (template: string, model: AsteriskModel): string {
  return `${GENERATED_HEADER}\n${eta.renderString(template, model)}`
}

function sanitizeDisplayText (value: string): string {
  const sanitized = value
    .normalize('NFKC')
    .replaceAll(/[^\p{L}\p{N} ._-]+/gu, ' ')
    .replaceAll(/\s+/g, ' ')
    .trim()
    .slice(0, 64)

  return sanitized || 'Unknown organization'
}
