import type {
  TelephonyDirectory,
  TelephonyDirectoryExchange,
} from '@hackfed/schemas/v1'

import { createHash } from 'node:crypto'
import { isIP } from 'node:net'

export interface AsteriskArtifacts {
  'extensions-inbound.conf': string
  'extensions-outbound.conf': string
  'iax.conf': string
}

export interface AsteriskModel {
  localPeerName: string
  localPrefix: string
  localShortName: string
  peers: AsteriskPeer[]
}

export type AsteriskModule = 'chan_iax2.so' | 'pbx_config.so'

export interface AsteriskPeer {
  codecs: TelephonyDirectoryExchange['codecs']
  context: string
  displayName: string
  host: string
  orgId: string
  peerName: string
  port: number
  prefix: string
  shortName: string
}

export interface BuildAsteriskModelOptions {
  exchangeId: string
  ignoredOrgs?: string[]
  orgId: string
}

const GENERATED_HEADER = `; This file is auto-generated by hackfedd.
; DO NOT EDIT THIS FILE MANUALLY. Your changes will be lost.
`

export function buildAsteriskModel (
  directory: TelephonyDirectory,
  options: BuildAsteriskModelOptions
): AsteriskModel {
  const localOrg = directory.orgs.find(org => org.orgId === options.orgId)
  if (!localOrg) {
    throw new Error(`Telephony directory does not contain local organization "${options.orgId}"`)
  }

  const localExchanges = localOrg.exchanges.filter(exchange => exchange.id === options.exchangeId)
  if (localExchanges.length !== 1) {
    throw new Error(
      `Telephony directory must contain exactly one local exchange "${options.orgId}/${options.exchangeId}"; found ${localExchanges.length}`
    )
  }

  const localExchange = localExchanges[0]
  if (!localExchange) {
    throw new Error('Local telephony exchange selection failed unexpectedly')
  }

  // Validate the local endpoint as well, even though it is not rendered as a peer.
  parseEndpoint(localExchange.endpoint)
  const localPeerName = makePeerName(options.orgId, options.exchangeId)
  const localPrefix = normalizePrefix(localExchange.prefix)
  const localShortName = sanitizeDisplayText(localOrg.orgId)
  const ignoredOrgs = new Set(options.ignoredOrgs)
  const peerNames = new Set([localPeerName])

  const peers = directory.orgs
    .flatMap(org => ignoredOrgs.has(org.orgId)
      ? []
      : org.exchanges.map(exchange => ({ exchange, org })))
    .filter(({ exchange, org }) => !(org.orgId === options.orgId && exchange.id === options.exchangeId))
    .map(({ exchange, org }): AsteriskPeer => {
      const { host, port } = parseEndpoint(exchange.endpoint)
      const codecs = localExchange.codecs.filter(codec => exchange.codecs.includes(codec))
      if (codecs.length === 0) {
        throw new Error(`No common codec for telephony exchange "${org.orgId}/${exchange.id}"`)
      }

      const peerName = makePeerName(org.orgId, exchange.id)
      if (peerNames.has(peerName)) {
        throw new Error(`Duplicate telephony exchange identity "${org.orgId}/${exchange.id}"`)
      }
      peerNames.add(peerName)

      return {
        codecs,
        context: `${peerName}-in`,
        displayName: sanitizeDisplayText(org.name),
        host,
        orgId: org.orgId,
        peerName,
        port,
        prefix: normalizePrefix(exchange.prefix),
        shortName: sanitizeDisplayText(org.orgId),
      }
    })
    .toSorted(comparePeers)

  const prefixes = new Set([localPrefix])
  for (const peer of peers) {
    if (prefixes.has(peer.prefix)) {
      throw new Error(`Duplicate telephony prefix "+${peer.prefix}"`)
    }
    prefixes.add(peer.prefix)
  }

  return { localPeerName, localPrefix, localShortName, peers }
}

export function makePeerName (orgId: string, exchangeId: string): string {
  const safeOrgId = orgId.toLowerCase().replaceAll(/[^a-z0-9]/g, '-')
  const slug = exchangeId
    .normalize('NFKD')
    .toLowerCase()
    .replaceAll(/[^a-z0-9]+/g, '-')
    .replaceAll(/^-+|-+$/g, '')
    .slice(0, 24) || 'exchange'
  const hash = createHash('sha256')
    .update(`${orgId}\0${exchangeId}`)
    .digest('hex')
    .slice(0, 12)

  return `hf-${safeOrgId}-${slug}-${hash}`
}

export function normalizePrefix (prefix: string): string {
  const normalized = prefix.startsWith('+') ? prefix.slice(1) : prefix
  if (!/^[1-9][0-9]*$/.test(normalized)) {
    throw new Error(`Invalid E.164 telephony prefix "${prefix}"`)
  }
  return normalized
}

export function parseEndpoint (endpoint: string): { host: string, port: number } {
  const ipv6 = /^\[([^\]]+)]:(\d{1,5})$/.exec(endpoint)
  const ipv4 = /^([^:]+):(\d{1,5})$/.exec(endpoint)
  const match = ipv6 ?? ipv4
  if (!match) {
    throw new Error(`Invalid telephony endpoint "${endpoint}"; expected [IPv6]:port or IPv4:port`)
  }

  const host = match[1]
  const portText = match[2]
  if (!host || !portText || isIP(host) === 0) {
    throw new Error(`Invalid IP address in telephony endpoint "${endpoint}"`)
  }

  const port = Number(portText)
  if (!Number.isSafeInteger(port) || port < 1 || port > 65_535) {
    throw new Error(`Invalid port in telephony endpoint "${endpoint}"`)
  }

  return { host, port }
}

export function renderAsteriskArtifacts (model: AsteriskModel): AsteriskArtifacts {
  return {
    'extensions-inbound.conf': renderInbound(model),
    'extensions-outbound.conf': renderOutbound(model),
    'iax.conf': renderIax(model),
  }
}

function comparePeers (left: AsteriskPeer, right: AsteriskPeer): number {
  return left.orgId.localeCompare(right.orgId) ||
    left.peerName.localeCompare(right.peerName) ||
    left.prefix.localeCompare(right.prefix) ||
    left.host.localeCompare(right.host) ||
    left.port - right.port
}

function renderIax ({ localPeerName, peers }: AsteriskModel): string {
  const sections = peers.map(peer => `; (${peer.orgId}) ${peer.displayName}
[${peer.peerName}]
type = friend
username = ${localPeerName}
host = ${peer.host}
port = ${peer.port}
context = ${peer.context}
qualify = yes
connectedline = yes
bandwidth = high
disallow = all
allow = ${peer.codecs.join(',')}
`)

  return `${GENERATED_HEADER}\n${sections.join('\n')}`
}

function renderInbound ({ localPeerName, localPrefix, localShortName, peers }: AsteriskModel): string {
  const connectedLineContext = `${localPeerName}-connected-line`
  const connectedLineHandler = `; Prefix connected-line names returned to remote callers
[${connectedLineContext}]
exten => s,1,Set(LOCAL(HF_CONNECTED_NAME)=\${CONNECTEDLINE(name)})
 same => n,GotoIf($[\${LEN(\${HF_CONNECTED_NAME})} = 0]?org-only)
 same => n,Set(CONNECTEDLINE(name,i)=${localShortName}: \${HF_CONNECTED_NAME})
 same => n,Return()
 same => n(org-only),Set(CONNECTEDLINE(name,i)=${localShortName})
 same => n,Return()
`
  const contexts = peers.map(peer => `; Calls from (${peer.orgId}) ${peer.displayName}
[${peer.context}]
exten => _${localPrefix}!,1,Set(HF_DESTINATION=\${FILTER(0-9,\${EXTEN})})
 same => n,GotoIf($[\${LEN(\${HF_DESTINATION})} = \${LEN(\${EXTEN})}]?valid-destination:invalid)
 same => n(valid-destination),Set(HF_CALLER_RAW=\${CALLERID(num)})
 same => n,GotoIf($["\${HF_CALLER_RAW:0:1}" = "+"]?caller-strip-plus)
 same => n,Set(HF_CALLER_BODY=\${HF_CALLER_RAW})
 same => n,Goto(caller-validate)
 same => n(caller-strip-plus),Set(HF_CALLER_BODY=\${HF_CALLER_RAW:1})
 same => n(caller-validate),Set(HF_CALLER_DIGITS=\${FILTER(0-9,\${HF_CALLER_BODY})})
 same => n,GotoIf($[\${LEN(\${HF_CALLER_DIGITS})} = \${LEN(\${HF_CALLER_BODY})} & \${LEN(\${HF_CALLER_DIGITS})} > 0]?valid-caller:invalid)
 same => n(valid-caller),GotoIf($["\${HF_CALLER_DIGITS:0:${peer.prefix.length}}" = "${peer.prefix}"]?normalized-caller:invalid)
 same => n(normalized-caller),Set(CALLERID(num)=+${peer.prefix}\${HF_CALLER_DIGITS:${peer.prefix.length}})
 same => n,Set(HF_CALLER_NAME=\${CALLERID(name)})
 same => n,Set(CALLERID(name)=${peer.shortName})
 same => n,GotoIf($[\${LEN(\${HF_CALLER_NAME})} = 0]?caller-name-ready)
 same => n,Set(CALLERID(name)=${peer.shortName}: \${HF_CALLER_NAME})
 same => n(caller-name-ready),Set(__HACKFED_INBOUND=1)
 same => n,Set(CONNECTED_LINE_SEND_SUB=${connectedLineContext},s,1)
 same => n,Gosub(HackfedIncomingRouter,s,1(\${HF_DESTINATION:${localPrefix.length}}))
 same => n,Hangup()
 same => n(invalid),Hangup(28)
`)

  return `${GENERATED_HEADER}\n${connectedLineHandler}\n${contexts.join('\n')}`
}

function renderOutbound ({ localPrefix, peers }: AsteriskModel): string {
  const foreignPrefixChecks = peers
    .map(peer => ` same => n,GotoIf($["\${HF_CALLER_DIGITS:0:${peer.prefix.length}}" = "${peer.prefix}"]?invalid)`)
    .join('\n')
  const canonicalAliases = [
    `exten => _+${localPrefix}.,1,Goto(hackfed-outbound,\${EXTEN:1},1)`,
    ...peers.map(peer => `exten => _+${peer.prefix}!,1,Goto(hackfed-outbound,\${EXTEN:1},1)`),
  ].join('\n')
  const loopback = `; Calls to the local Hackfed prefix
exten => _${localPrefix}.,1,Dial(PJSIP/\${EXTEN:${localPrefix.length}},30,rT)
 same => n,Hangup()
`
  const routes = peers.map(peer => `; Calls to (${peer.orgId}) ${peer.displayName}
exten => _${peer.prefix}!,1,GotoIf($["\${HACKFED_INBOUND}" = "1"]?invalid)
 same => n,Set(HF_DESTINATION=\${FILTER(0-9,\${EXTEN})})
 same => n,GotoIf($[\${LEN(\${HF_DESTINATION})} = \${LEN(\${EXTEN})}]?valid-destination:invalid)
 same => n(valid-destination),Set(HF_CALLER_RAW=\${CALLERID(num)})
 same => n,GotoIf($["\${HF_CALLER_RAW:0:1}" = "+"]?caller-strip-plus)
 same => n,Set(HF_CALLER_HAD_PLUS=0)
 same => n,Set(HF_CALLER_BODY=\${HF_CALLER_RAW})
 same => n,Goto(caller-validate)
 same => n(caller-strip-plus),Set(HF_CALLER_HAD_PLUS=1)
 same => n,Set(HF_CALLER_BODY=\${HF_CALLER_RAW:1})
 same => n(caller-validate),Set(HF_CALLER_DIGITS=\${FILTER(0-9,\${HF_CALLER_BODY})})
 same => n,GotoIf($[\${LEN(\${HF_CALLER_DIGITS})} = \${LEN(\${HF_CALLER_BODY})} & \${LEN(\${HF_CALLER_DIGITS})} > 0]?caller-digits:invalid)
 same => n(caller-digits),GotoIf($["\${HF_CALLER_DIGITS:0:${localPrefix.length}}" = "${localPrefix}"]?caller-complete)
 same => n,GotoIf($[\${HF_CALLER_HAD_PLUS} = 1]?invalid)
${foreignPrefixChecks}
 same => n,Set(HF_CALLER_DIGITS=${localPrefix}\${HF_CALLER_DIGITS})
 same => n(caller-complete),Set(CALLERID(num)=+\${HF_CALLER_DIGITS})
 same => n,Dial(IAX2/${peer.peerName}/\${HF_DESTINATION},30,rT)
 same => n,Hangup()
 same => n(invalid),Hangup(28)
`)

  return `${GENERATED_HEADER}\n[hackfed-outbound]\n; Accept canonical E.164 dial strings and normalize them for internal routing
${canonicalAliases}\n\n${loopback}\n${routes.join('\n')}`
}

function sanitizeDisplayText (value: string): string {
  const sanitized = value
    .normalize('NFKC')
    .replaceAll(/[^\p{L}\p{N} ._-]+/gu, ' ')
    .replaceAll(/\s+/g, ' ')
    .trim()
    .slice(0, 64)

  return sanitized || 'Unknown organization'
}
